### ISSUE TITLE
So what happened to the Either.unite method?

### ISSUE THREAD

**Issue by hicnar** [avdosev/either_dart#2]
Any guidelines how to migrate existing code?

**Comment by avdosev** [comment]
change unite -> fold

**Comment by hicnar** [comment]
Thanks for prompt reply, can see it now! 
I think a slightly better way to handle breaking changes like that would be deprecating the unite at the same time when its replacement (fold) was introduced just to allow people who use some time to react (deprecated method warning certainly draws attention), then remove it after two or three few releases. 
Anyways thanks for clarification!
