### ISSUE TITLE
Better type for Future<T> fold<T>

### ISSUE THREAD

**Issue by lukasbalaz** [avdosev/either_dart#6]
https://github.com/avdosev/either_dart/blob/06b4361e99191008dcf6381555f77aca05a428a1/lib/src/future_extension.dart#L57-L59

I am quite new to dart so I may be wrong here (that's why I am creating an issue rather then pull request) but shouldn't `fnL` and `fnR` return `FutureOr<T>` instead of `T`?

```dart
Future<T> fold<T>(FutureOr<T> Function(L left) fnL, FutureOr<T> Function(R right) fnR) {
  return this.then((either) => either.fold(fnL, fnR));
}
```

This is what `this.then()` actually expects and it would allow us to do something like this:

```dart
bool success = await getStatusAsync()
  .fold(
    (error) async {
      await saveErrorAsync(error);
      return false;
    },
    (status) async {
      await saveStatusAsync(status);
      return true;
    },
);
```
(it's just and example and my usecase is actually quite different but I also need to fold both left and right to different futures of the same type)

**Comment by avdosev** [comment]
You are right. Using FutureOr in this case is justified. I will take this point into account and make a new release.

**Comment by avdosev** [comment]
I published a new release, you are welcome to use it.
