### ISSUE TITLE
Sealed Classes

### ISSUE THREAD

**Issue by dballance** [avdosev/either_dart#7]
https://dart.dev/language/class-modifiers#sealed

Admittedly I haven't dug too deep here - but seems like a `sealed` annotation would be a nice addition for this lib. 

Might need to be a separate package to maintain compatibility with Dart < 3.0.

Happy to take a stab at it at some point in the next week or two if you'd like!

**Comment by avdosev** [comment]
I agree, this is a useful application of the new language feature for this library.

> Might need to be a separate package to maintain compatibility with Dart < 3.0.

Probably some users are not using the newest version of dart, but in my opinion creating a separate package makes no sense, considering that switching to a new version is not difficult, and the current main part of the library has enough api for most cases.

**Comment by avdosev** [comment]
ready in 1.0.0 release

**Comment by dballance** [comment]
Excellent!

I agree that it should stay in this package - was just unsure the appetite for the breaking change. Seems like 1.x rev is a good way to handle it - given that people should be moving to Dart 3.0 soon and the existing release API is plenty stable.

🍻
